feat template: create service template with pg and grpc
userver-framework/pg_grpc_service_template pull request #1
Opened 2022-11-14 11:23 UTC by alexiprof

create service template with pg and grpc

2022-11-14 11:30 UTC, apolukhin requested changes

2022-11-14 11:30 UTC, apolukhin commented on configs/static_config.yaml.in
> +             listener:                 # configuring the main listening socket...
Отступ в 4 символа предпочтительнее

2022-11-14 11:30 UTC, apolukhin commented on src/hello_client.hpp
> +class HelloClient final : public userver::components::LoggableComponentBase {
Этот класс не нужен

2022-11-14 11:30 UTC, apolukhin commented on src/main.cpp
> +  pg_grpc_service_template::AppendHelloHttpProxy(component_list);
Лишнее

2022-11-14 13:32 UTC, alexiprof commented on configs/static_config.yaml.in
> +             listener:                 # configuring the main listening socket...
поправил

2022-11-14 13:32 UTC, alexiprof commented on src/hello_client.hpp
> +class HelloClient final : public userver::components::LoggableComponentBase {
не этот, а HelloHttpProxy - убрал его

2022-11-14 14:27 UTC, apolukhin requested changes

2022-11-14 14:27 UTC, apolukhin commented on CMakeLists.txt
> +	src/hello_client.hpp
Кажется тут табы вместо пробелов

2022-11-14 14:27 UTC, apolukhin commented on Makefile.local
> +CMAKE_COMMON_FLAGS += -DUSERVER_FEATURE_GRPC=1 -DUSERVER_FEATURE_GRPC_CHANNELZ=0
Антон сделал автодетект, можно опцию убирать

2022-11-14 14:27 UTC, apolukhin commented on proto/handlers/hello.proto
> +	rpc SayHelloMock(HelloRequest) returns(HelloResponse) {}
Странная ручка. Давай без неё. Сразу зови client_.SayHello из верхней ручки

2022-11-14 14:27 UTC, apolukhin commented on src/hello_client.cpp
> +userver::yaml_config::Schema HelloClient::GetStaticConfigSchema() {
Проверь, что валидация параметров в коде включкна

2022-11-14 14:27 UTC, apolukhin commented on tests/conftest.py
> +    'pytest_userver.plugins.samples',
Лишнее

2022-11-14 14:27 UTC, apolukhin commented on tests/conftest.py
>      'pytest_userver.plugins',
Достаточно этого плагина и самого нижнего. Но надо апнуть userver

2022-11-14 14:27 UTC, apolukhin commented on README.md
>  Template of a C++ service that uses [userver framework](https://github.com/userver-framework/userver) with PostgreSQL.
with PostgreSQL and gRPC.

2022-11-14 15:40 UTC, alexiprof commented on CMakeLists.txt
> +	src/hello_client.hpp
поправил

2022-11-14 15:40 UTC, alexiprof commented on Makefile.local
> +CMAKE_COMMON_FLAGS += -DUSERVER_FEATURE_GRPC=1 -DUSERVER_FEATURE_GRPC_CHANNELZ=0
поправил

2022-11-14 15:40 UTC, alexiprof commented on proto/handlers/hello.proto
> +	rpc SayHelloMock(HelloRequest) returns(HelloResponse) {}
ок

2022-11-14 15:41 UTC, alexiprof commented on tests/conftest.py
>      'pytest_userver.plugins',
поправил

2022-11-14 15:42 UTC, alexiprof commented on README.md
>  Template of a C++ service that uses [userver framework](https://github.com/userver-framework/userver) with PostgreSQL.
поправил

2022-11-14 15:54 UTC, alexiprof commented on src/hello_client.cpp
> +userver::yaml_config::Schema HelloClient::GetStaticConfigSchema() {
проверил

2022-11-14 16:32 UTC, apolukhin requested changes

2022-11-14 16:32 UTC, apolukhin commented on Makefile.local
> +CMAKE_COMMON_FLAGS += -DUSERVER_FEATURE_GRPC=1 -DUSERVER_FEATURE_GRPC_CHANNELZ=0
Кажется что нет)

2022-11-14 16:32 UTC, apolukhin commented on src/hello.cpp
> +/*void Hello::SayHelloMock(
Удоли)

2022-11-14 16:32 UTC, apolukhin commented on src/hello.hpp
> +  // void SayHelloMock(handlers::api::HelloServiceBase::SayHelloMockCall& call,
Лишнее

2022-11-14 16:32 UTC, apolukhin commented on tests/test_grpc_server.py
> +        return hello_protos.HelloResponse(
Сюда напрашивается assert

2022-11-14 16:32 UTC, apolukhin commented on tests/test_grpc_server.py
> +    async def mock_say_hello(request, context):
Лучше назвать mock_grpc_service

2022-11-14 16:32 UTC, apolukhin commented on tests/test_grpc_server.py
> +import pytest
Лучше файл назвать test_hello.py , ведь тут и клиент и сервер

2022-11-14 16:32 UTC, apolukhin commented on src/hello_client.cpp
> +            the service endpoint (URI). We talk to our own service,
```suggestion
            Some other service endpoint (URI). 
```

2022-11-14 16:32 UTC, apolukhin commented on src/hello_client.cpp
> +            which is kind of pointless, but works for an example
Лишнее

2022-11-14 20:40 UTC, alexiprof commented on src/hello.cpp
> +/*void Hello::SayHelloMock(
+

2022-11-14 20:41 UTC, alexiprof commented on src/hello.hpp
> +  // void SayHelloMock(handlers::api::HelloServiceBase::SayHelloMockCall& call,
+

2022-11-14 20:43 UTC, alexiprof commented on tests/test_grpc_server.py
> +        return hello_protos.HelloResponse(
+

2022-11-14 20:43 UTC, alexiprof commented on tests/test_grpc_server.py
> +    async def mock_say_hello(request, context):
+

2022-11-14 20:43 UTC, alexiprof commented on tests/test_grpc_server.py
> +import pytest
+

2022-11-15 04:45 UTC, apolukhin commented on tests/test_hello.py
> +        assert request.name
```suggestion
        assert request.name == 'mock_userver'
```

2022-11-15 04:45 UTC, apolukhin approved these changes

2022-11-15 09:03 UTC, merged